name: Telebot-Games-Parser

on:
    push:

env:
    TOKEN: ${{ secrets.TOKEN }}

jobs:
    Run-bot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt
            - name: Run tests
              run: pytest main.py src/tests
